import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { Home } from "lucide-react";
import "./globals.css";
import { Providers } from "@/components/Providers";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          {children}
        </Providers>
        <Link 
          href="/" 
          className="fixed bottom-4 right-4 sm:bottom-6 sm:right-6 bg-card border border-border text-primary p-3 sm:p-4 rounded-full shadow-2xl hover:bg-primary hover:text-primary-foreground transition-all z-50 group active:scale-90"
          title="Início"
        >
          <Home className="w-5 h-5 sm:w-6 sm:h-6" />
          <span className="absolute right-full mr-3 bg-secondary border border-border text-foreground px-2 py-1 rounded text-xs opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap">
            Voltar ao Início
          </span>
        </Link>
      </body>
    </html>
  );
}
